#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Directories
SCRIPTS_DIR="/custom-cont-post.d"

# Make sure postinstall directory exists and has files in it
if [[ -e "${SCRIPTS_DIR}" ]] && [[ -n "$(/bin/ls -A ${SCRIPTS_DIR} 2>/dev/null)" ]]; then
    echo "[postinstall] Files found, executing"
    for SCRIPT in "${SCRIPTS_DIR}"/*; do
        NAME="$(basename "${SCRIPT}")"
        if [[ -f "${SCRIPT}" ]]; then
            echo "[postinstall] ${NAME}: executing..."
            /bin/bash "${SCRIPT}"
            echo "[postinstall] ${NAME}: exited $?"
        elif [[ ! -f "${SCRIPT}" ]]; then
            echo "[postinstall] ${NAME}: is not a file"
        fi
    done
else
    echo "[postinstall] No custom files found, skipping..."
fi
