name: Sync Github and Jira release

on:
  push:
    tags:        
      - '*'

jobs:
  create-jira-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create-jira-release
        uses: Medsien/release-to-jira@main
        with:
          jira_server: "https://home-organisation.atlassian.net/"
          jira_project: "MEDIA"
          jira_user: ${{ secrets.JIRA_USER_EMAIL }}
          jira_token: ${{ secrets.JIRA_API_TOKEN }}
